/*
 * Which SPACE a position is in.
 *
 * Every position, area, path and distance in this domain names a spatial
 * context, and two of them may only be compared when the names match. The
 * reason is that the engine has no idea what a context IS: it is a host's
 * scene, map, floor, pocket dimension or ship interior, identified by an
 * opaque string the host chooses and the engine never parses.
 *
 * Without that name, "12 metres" is a number with no space attached, and the
 * first bug is silent rather than loud — a Skill with a 15 m Range resolving
 * against a target standing on a different map, at coordinates that happen to
 * be close to the actor's. Refusing the comparison is the only answer that
 * cannot be quietly wrong, because the engine genuinely does not know whether
 * two contexts are adjacent, nested, the same place at two times, or
 * unrelated. A host that DOES know can supply a fact saying so; see facts.ts.
 */

import type { EngineError } from "../infrastructure/diagnostics";


/**
 * Opaque identity of one coherent space.
 *
 * Not parsed, not structured, and never generated by the engine. A host may
 * use a scene id, a UUID, or "the-ship-hold" — the engine only ever asks
 * whether two of them are the same string.
 */
export type SpatialContextId = string;


/** Anything positioned in space names the space it is positioned in. */
export interface SpatiallyContextual {
  readonly contextId: SpatialContextId;
}


export function isValidSpatialContextId(
  value: unknown,
): value is SpatialContextId {
  return typeof value === "string" && value.trim().length > 0;
}


export function sameSpatialContext(
  left: SpatiallyContextual,
  right: SpatiallyContextual,
): boolean {
  return left.contextId === right.contextId;
}


/**
 * The error a comparison across two spaces produces.
 *
 * Shared rather than written at each call site so that a host filtering for
 * this specific situation — offering to resolve the two contexts, say — has
 * one code to match on.
 */
export function spatialContextMismatchError(
  left: SpatialContextId,
  right: SpatialContextId,
): EngineError {
  return {
    code: "spatial.context.mismatch",
    message:
      "These positions are in different spatial contexts and cannot be compared.",
    audience: "developer",
    required: "one shared spatial context",
    actual: `${left} vs ${right}`,
    resolution:
      "Supply both positions in one context, or have the host resolve the relationship between the two contexts and supply the distance as a fact.",
  };
}
